# Generated by Django 4.2.15 on 2024-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_course_teacher_student_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(default="No content provided"),
        ),
    ]
